[package]
name = "working_with_mongodb"
version = "0.1.0"
edition = "2021"

[dependencies]
bson = { version = "2.11.0", features = ["chrono-0_4"] }
chrono = { version = "0.4.38", features = ["serde"] }
mongodb = "3.0.1"
serde = { version = "1.0.208", features = ["derive"] }
tokio = "1.39.3"
